### ISSUE TITLE
PyAT: Significantly slower performance when looping through lattice

### ISSUE THREAD

**Issue by lcarver** [atcollab/at#129]
[lattice.zip](https://github.com/atcollab/at/files/3579400/lattice.zip)

Hello,

I have noticed a significant reduction in performance for some quite basic operations on the Lattice object. This reduction has been introduced at some point since the end of June. 

Please see below for a comparison between the master branch (up-to-date) and the errors_correction branch (not synched with master since end of June). I have attached a lattice called betamodel that can be used with the code below.

`import at, time`
`ring = at.load_mat('./betamodel.mat', key='betamodel')`
`ring = at.Lattice(ring) `
`bpmElems = ring.get_elements('BPM*')`
`start = time.time()`
`ind = ring.index(bpmElems[-1])`
`print(time.time() - start)`

If we compare the computation time (s) between the master and the errors_correction branch:
master:  2.9074273109436035 
errors_correction: 0.00014591217041015625

Cheers,
Lee

@swhite @carmignani

**Comment by willrogers** [comment]
I expect @lfarv might have some ideas about this, but I think he is away at the moment. I don't immediately know what's happening here, but clearly 2.9 seconds is a long time.

**Comment by lfarv** [comment]
`ind = ring.index(bpmElems[-1])` tests equality of the element `bpmElems[-1]` with all elements of `ring`. We recently introduced a new method `Element.__eq__` which implements that by building the element `repr` string. This is very slow compared to the previous behaviour comparing element `id`s.

I think we should revert to the previous behaviour, which is adequate for most cases (including @lcarver's search).

**Comment by willrogers** [comment]
This is unfortunate, but I suppose I agree. The difference is that two different elements with the same parameters won't compare as equal, and I would prefer them to, but this performance problem is too big.

**Comment by lfarv** [comment]
#131 reverts to the previous behaviour. In the future, one could create another `Element` method (`isequal` for instance) to compare element parameters, if necessary.

**Comment by lcarver** [comment]
Thank you Laurent and Will for your work.

**Comment by willrogers** [comment]
Can we close this issue?

**Comment by lcarver** [comment]
Yes, I just checked on my side and the problem is no longer seen.
