### ISSUE TITLE
atradoff 

### ISSUE THREAD

**Issue by simoneliuzzo** [atcollab/at#147]
`atradoff(LATTICE)`

does not actually set off radiation in all elements by default 

`atradoff(LATTICE,'','auto','auto')`

must be used and it is not so intuitive. 

I would suggest to default the behaviour of atradoff to the result of  `atradoff(LATTICE,'','auto','auto')`

**Comment by lnadolski** [comment]
to be corrected in #168

**Comment by willrogers** [comment]
This one has been fixed.
