### ISSUE TITLE
Problems with athelp

### ISSUE THREAD

**Issue by willrogers** [atcollab/at#160]
It may be that I don't understand, but `athelp` doesn't seem to be working properly for me.

Each time I run `athelp` it generates documentation, because it can't find a file called `atdoc.mat`. However, it creates a file called `helpdoc.mat`.

If I change all the references to `helpdoc.mat` it seems to work correctly. Is this a bug and should I fix it?

Both `helpdoc.mat` and `atdoc.mat` are in `.gitignore`, so maybe they are both required.

Any ideas @lnadolski?

**Comment by lnadolski** [comment]
This is bug.
Corrected [here](https://github.com/atcollab/at/commit/0a923e59acf8ee561f13db601c9a28a21663f034)

**Comment by lnadolski** [comment]
corrected

**Comment by willrogers** [comment]
Thanks.
