### ISSUE TITLE
atcavityon doesn't set passmethod correctly

### ISSUE THREAD

**Issue by TeresiaOlsson** [atcollab/at#161]
The function atcavityon doesn't set the passmethod correctly. It sets it to {'CavityPass'  'auto'  ''}, which leads to an error. I have to manually set the passmethod to CavityPass to fix it.

Anyone else having this problem or it could be related to Matlab version? I am using R2020a.

**Comment by carmignani** [comment]
Hello, I think it was a bug. It should be fine like this, but maybe @lnadolski can have a look, because he wrote the functions.

**Comment by lnadolski** [comment]
to be corrected in issues/168

**Comment by willrogers** [comment]
I think this one has been fixed.
