### ISSUE TITLE
precision of m66 and m44 matrix derivation

### ISSUE THREAD

**Issue by swhite2401** [atcollab/at#189]
The steps to compute the 44 and 66 matrices are presently set to:

XYDEFSTEP = 6.055454452393343e-006
DPSTEP = 6.055454452393343e-006

in pyat and AT.

@simoneliuzzo has found that multiplying matrices of a split ring does not exactly return the matrix of the full ring.
This can be solved by reducing the steps to 1.0e-8.

Is there any good reason for these values or are they purely historical?
Are they used elsewhere in the code?

**Comment by lfarv** [comment]
Addressed in #199

**Comment by lnadolski** [comment]
sorry for the late answer.
The step size is optimized and given in numerical recipes
