### ISSUE TITLE
Violation of Naff license

### ISSUE THREAD

**Issue by matsievskiysv** [atcollab/at#197]
This repo contains a number of licenses including [Naff](https://raw.githubusercontent.com/atcollab/at/master/doc/licenseFiles/NaffLicense.txt), which has the following line:
> !**************************************************************************
!  THIS PROGRAMM  CANNOT BE COPIED, 
!  DISTRIBUTED NOR MODIFIED WITHOUT THE AGREEMENT OF THE AUTHOR.
!**************************************************************************

I guess that this makes this repo illegal.
I, for one, forked and modified code without asking anybody.

**Comment by lfarv** [comment]
@lnadolski: Can you comment on the possibility to create forks of AT?

**Comment by lnadolski** [comment]
This header is indeed from legacy.
This is fine to use NAFF in the context of accelerators.
Forks as allowed.

**Comment by matsievskiysv** [comment]
Then remove this phrase maybe?
