### ISSUE TITLE
Inconsistent radon radoff between matlab and python

### ISSUE THREAD

**Issue by swhite2401** [atcollab/at#276]
In `matlab` element types are detected looking at attributes likes `BendingAngle`, `PolynomB` etc... while in python it checks the class.
This leads to issues when a lattice in `matlab` can be generated with radiations on in multipoles. This lattice if imported in `pyAT` cannot be used as `ring.radiation_off(`) does not handle multipoles.

It would to make sure the two implementations are consistent. As a temporary fix I will turn radiations in multipoles in `ring.radiations_off()`

**Comment by willrogers** [comment]
Can this be closed?

**Comment by swhite2401** [comment]
Yes I will close it, matlab cannot handle classes anyway
