### ISSUE TITLE
Plotting the closed orbit

### ISSUE THREAD

**Issue by elafmusa** [atcollab/at#286]
Hi everyone 

I'm new with AT using python, currently, i want to plot a closed orbit of an accelerator.

I used the following code:

**pin = [np.array([x0]),np.array([xp0])]
new_pin = np.concatenate((pin, [np.zeros(1)], [np.zeros(1)], [np.zeros(1)], [np.zeros(1)]))
pout = at.track.lattice_pass(ring1, new_pin.copy(), nturns=1000, refpts=[len(ring1)])
x=pout[0,0,0,:]
xp=pout[1,0,0,:]

bpm_indexes = get_refpts(ring1, 'BPM*')
orb0, orb = ring1.find_orbit4(dp=0, refpts=bpm_indexes)

plot(x,orb,"*")**

but it gives me the " x and y must have same first dimension" error 

Could you please give me a feedback on this.

Thank you in advance

**Comment by swhite2401** [comment]
Dear @elafmusa, 
You are trying to plot 2 vectors of different lengths which is not allowed.

To plot the horizontal closed orbit versus s you may try:

```
s = ring.get_s_pos(refpts=refpts)
_, orbit = ring.find_orbit(refpts=refpts)
plot(s,orbit[:,0])
```
I hope this helps. 
Concerning questions on code usage I would suggest to use discussions instead.
