### ISSUE TITLE
Integral tolerances in Touschek Piwinski lifetime in matlab

### ISSUE THREAD

**Issue by carmignani** [atcollab/at#325]
I did some Touschek lifetime simulations varying different parameters for the ESRF storage ring and I noticed that with the default parameters often we get not precise results, at least for very large vertical emittances.
 
I attach here a plot of the Touschek lifetime computed with TouschekPiwinskiLifeTime as a function of vertical emittance.
The blue is using the method "quad", that is not recommended by matlab, but it gives the good results. 
The other ones are instead using the "integral" method, but changing the relative and absolute tolerances. The red curve is with the default values of tolerances of "integral", which is what we get by running TouschekPiwinskiLifeTime with default parameters.

I think the best is to allow the user to give the absolute and relative tolerances as input (now you have to modify the function to change the tolerances) and to give a smaller number as default. It seems like 1e-16 and 1e-12 are small enough for the case I studied.

![Screenshot 2021-11-09 at 15 47 37](https://user-images.githubusercontent.com/14995243/140945924-27d6a43c-e662-4ca9-9a84-fe955e06e1e3.png)

**Comment by simoneliuzzo** [comment]
I see only benefit in this change.

**Comment by swhite2401** [comment]
I agree. Why is quad not recommended? Looking at these curves I would just set it as default...
Btw, I did an implementation in python using `integrate.quad` that I still need to push at some point that seems to work very well

**Comment by carmignani** [comment]
I don't know exactly why quad is not recommended: this is what they write in the documentation.
![Screenshot 2021-11-10 at 09 12 51](https://user-images.githubusercontent.com/14995243/141075032-66838715-8e37-4572-bbcd-ddf5b3e0e837.png)

**Comment by lfarv** [comment]
See #326 for an answer to this!

**Comment by lfarv** [comment]
Solved in #326
