### ISSUE TITLE
Time-out in tests

### ISSUE THREAD

**Issue by lfarv** [atcollab/at#356]
For a few days, we have been suffering from time-outs in the GitHub tests. From a 1st analysis:
- it happens only for Ubuntu and MacOS, never for Windows,
- it's not always for the same configuration (platform/python version). Re-running the tests fails differently,
- it's always hanging in `test_patpass.py` (parallel python)

So the questions are:
- is it related to the last modification of `patpass` (which succeeded all tests when it was merged)?
- should we take out this test until we understand ? It's penalising all other developments…

**Comment by swhite2401** [comment]
Ok for me to remove it from tests, when it is hanging do you get an error message?

**Comment by lfarv** [comment]
@swhite2401: no error, no message, it's just hanging until the job is killed (after 6 hours !). You can have a look at all the recent tests…

I would also skip the test, but for sure it needs investigations, this makes `patpass` unsafe.

**Comment by swhite2401** [comment]
Ok i'll take lok I agree this is worrying

**Comment by lfarv** [comment]
A temporary workaround is set in #357, but the problem is still there. So I keep the issue open.

Could it be due to some change on GitHub? It started abruptly 2 days ago (25/01/2022, around 12:00), while `patpass` was modified 9 days ago…
Simultaneously, there seems to be a lack of MacOS runners, macOS jobs wait for long before getting an available one…
