### ISSUE TITLE
Memory allocation error when changing Nslice in WakefieldPass

### ISSUE THREAD

**Issue by lcarver** [atcollab/at#360]
When defining a wake element, a value for Nslice is given. For example
```
from at.collective.wake_elements import LongResonatorElement
freq=10e9; qfactor=1; Rs=1e4;
welem = LongResonatorElement('wake', ring, srange, freq, qfactor, Rs, Nslice=100)
```
If the value of Nslice is then changed i.e.
```
welem.Nslice=300
```
Then when you are tracking it will return a memory allocation error and give a segmentation fault. This is because the buffers 'TurnHistory*' are defined for the original value of Nslice and not the new one. 

Possible fixes: 
When Nslices is changed then the buffers must be updated. This will have a knock on effect to some other parameters too.
or Error catching and informative error messages.

**Comment by lfarv** [comment]
Corrected in #362
