### ISSUE TITLE
orbit response matrix in PyAT

### ISSUE THREAD

**Issue by elafmusa** [atcollab/at#389]
I have two questions about measuring the orbit response matrix in PyAT:

The first question: 
I want a confirmation that i a, following the write steps in calculating Cyy and Cyx, i do it as following:

**def ORM_y(dkick, ring):

    cyy = []
    cyx = []

    correctors_indexes = get_refpts(ring, elements.Corrector)
    bpm_indexes = get_refpts(ring, elements.Monitor)

    for j in range(len(correctors_indexes)):
        ring[correctors_indexes[j]].KickAngle[1] = dkick
        lindata0, tune, chrom, lindata = ring.linopt(get_chrom=True, refpts=bpm_indexes)
        s_pos = lindata['s_pos']
        closed_orbit = lindata['closed_orbit']
        closed_orbitx = lindata['closed_orbit'][:, 0]
        closed_orbity = lindata['closed_orbit'][:, 1]
        betax = lindata['beta'][:, 0]
        betay= lindata['beta'][:, 1]
        dx = lindata['dispersion'][:, 0]
        dy= lindata['dispersion'][:, 1]

        cyy.append(closed_orbity)
        cyx.append(closed_orbitx

        ring[correctors_indexes[j]].KickAngle[1] = 0.00

    Cyy = np.squeeze(cyy) / dkick
    Cyx = np.squeeze(cyx) / dkick

    return Cyy, Cyx**

The second question:

I am working on implementing LOCO algorithm, in that i came by step of calculation the dq where i do the same ORM calculations above but with the quadruples instead of the correctors by changing the quadrupoles strengths and measuring the closed orbits.
My question is how can i deal with the quadrupole as in the case of corrector above where i used index 0 and 1 to differentiate between the kike in the x and y plane hence the calculation of the Cx and CY. In the case of the quadrupoles how can i use this index to calculate the x and y ORM when the quadrupole strength is not  splitable.

**Comment by swhite2401** [comment]
Hello, you may use `PolynomB` and `PolynomA` attributes instead, these are the coefficiants of the polynomial expension
