### ISSUE TITLE
atavedata with small K

### ISSUE THREAD

**Issue by ZeusMarti** [atcollab/at#399]
Hi all,

I recently run into unexpected results when using atavedata on a lattice with errors (also with transverse displacements) where the optics had been corrected adding small quadupolar components in the sextupoles. The resulting average betas and dispersion where totally off. The implemented formulas are perfectly correct but make use of the twiss parameters before (beta0 for example) and after (beta1 for example) each magnet. I think that makes the result very inaccurate in the presence of displacement errors in sextupoles. I came up with a workaround that maybe you can implement as well. The functions would be modified as follows:

```
function avebeta=betadrift(beta0,alpha0,L)
        gamma0=(alpha0.*alpha0+1)./beta0;
        avebeta=beta0-alpha0.*L+gamma0.*L.*L/3;
end

function avebeta=betafoc(beta0,alpha0,K,L)
        gamma0=(alpha0.*alpha0+1)./beta0;
        avebeta=((beta0+gamma0./K).*L+(beta0-gamma0./K).*sin(2.0*sqrt(K).*L)./sqrt(K)/2.0+(cos(2.0*sqrt(K).*L)-1.0).*alpha0./K)./L/2.0;
end

function avedisp=dispfoc(disp0,dispp0,K,L)
        avedisp=(disp0.*(sin(sqrt(K).*L)./sqrt(K))+dispp0.*(1-cos(sqrt(K).*L))./K)./L;
end
```

And function calls would then be:

```
avebeta(lg,:)=betadrift(beta0,alpha0,L2);
avebeta(sel,:)=betafoc(beta0(foc,:),alpha0(foc,:),K2(foc,:),L2(foc,:));
avedisp(sel,[1 3])=dispfoc(disp0(foc,[1 3]),disp0(foc,[2 4]),K2(foc,:),L2(foc,:));
```
I hope this makes sense to you,

Zeus

**Comment by lfarv** [comment]
@ZeusMarti : What I understand from you modifications is that you recompute the final values from the initial ones instead of using the values previously computed by `atlinopt`. This looks perfectly valid. But do you understand why this makes a difference ? What `atlinopt` does is exactly the same (or should be…).

However the comparison of both versions revealed a bug, in both: for dipoles, the contribution of the curvature to the horizontal focusing is not properly taken into account:
- in the original version, the "final" values are correct (resulting from `atlinopt`), but the horizontal K value is missing a 1/&rho;<sup>2</sup> term.  And dipoles without focusing are considered as drifts (K=0),
- in your modified version, non-focusing dipoles are also considered as drifts, and for focusing ones, the 1/&rho;<sup>2</sup> term is completely ignored.

For large machines, this is usually a small error, but I think that this has to be cleaned.

Coming back to your point, do you understand where the difference comes from? Concerning the magnitude of K, there is no special treatment in any versions: either K is zero, or not, whether it it small or large…

**Comment by ZeusMarti** [comment]
@lfarv 

I have not studied this issue in every detail, still I'll do my best to explain what I have observed. Yes, the large discrepancies (sometimes the resulting average betas are negative) happen at displaced sextupoles with small PolynomB(2) (K) values. The main quadrupoles and dipoles results did not draw my attention so far, but as you said for dipoles the 1/rho2 term should be added, that may be relevant some times.

In my case of study, sextupoles have small non zero K, they are not considered as drifts so the 'betafoc' function is used. With the same lattice if PolynomB(2) is set to zero in that element (betadrift is used) then the discrepancy is negligible (as negligible as the small displacements that are introduced I guess). My feeling is that the problem comes from the term (alpha1-alpha0)/K for small K values. For displaced sextuples with small K value both numerator and denominator are small numbers, if K does not include the sextupole feed-down, that ratio does not give consistent values. I have tried to include the feed-down effect adding the following lines:

```
        q=atgetfieldvalues(ring(qp),'PolynomB',{2});
        m=atgetfieldvalues(ring(qp),'PolynomB',{3});
        dx=(atgetfieldvalues(ring(qp),'T2',{1})-atgetfieldvalues(ring(qp),'T1',{1}))/2;
        K(foc)=q-2*m.*dx;
```

This solves the problem in lattices with just one one sextupole displaced and no much orbit at the sextupoles but not in lattices with realistic errors and corrections. To solve the problem in the general case I guess one should add also the average orbit position at each magnet.

If you want and are willing to be patient (I'm not a frequent git user and every time I do this I have to start over) I can try to come up with a pull request for an atavedata function modification which should include all that we are discussing:

- dipole focusing, also edge focusing?
- displaced sextupole feed-down taking into account orbit at sextupoles.
- Am I missing something? Maybe a quadrupole rotation cos(theta) term? Or that would be too picky?
- Just in case we miss something I think it is more prudent to avoid the  (alpha1-alpha0)/K, what do you think?

Other wise you can implement your own version, let me know what you prefer!

**Comment by lfarv** [comment]
@ZeusMarti : your explanation is convincing ! But I think the solution is even more complicated. In your attempt to include the sextupole feed-down:

`dx=(atgetfieldvalues(ring(qp),'T2',{1})-atgetfieldvalues(ring(qp),'T1',{1}))/2;`

you are still missing the closed orbit: what matters is the distance between the closed orbit and the magnet axis. And the closed orbit is completely ignored in `atavedata`'s computation…

We could imagine a preliminary tracking loop which would compute the closed orbit in the middle of each magnet, get the "effective" focusing from the full PolynomB (think of possible sextupole or higher components in quads or dipoles), and then apply the present formulae. Which cannot be vectorised any more…

Obviously, the present code is intended to be applied to "perfect" machines. The focusing induced by the closed orbit/displacement in sextupoles is usually small enough and the drift approximation acceptable, except when combined with a small K value as in your case. A more general version seems to be a major modification. If you think it's worth the effort, feel free to propose an upgrade (I'm indeed patient!). In the mean time, a warning in the function's help looks advisable. I'll prepare that.

**Comment by ZeusMarti** [comment]
Sorry for the delay and also sorry for the way I implemented the file change. After downloading the last at version yesterday night I just did a "git push origin" I had just changed the "atavedata.m" file I guess I didn't breake anything but actually my idea was to let you accept that cange. I just have myself to blame but maybe I have too much permisions given my low level git skills...

**Comment by lfarv** [comment]
@ZeusMarti: That's indeed not the safe way to work ! Instead, what you should do is:
1. Create a new branch for development. Let's call it "atavedata"
   ```git checkout atavedata```
2. Work locally on this branch. Nobody cares…
3. Push this branch to the repository:
   ```git push origin atavedata```
   Now everybody call try it and check,
4. When it's ready, open a  "pull request": this is a request for merging into the main branch, it allows to double-check everything,
5. Finally merge the branch into the main one ("master").

So now, I reverted the "master" branch to where it was before you commit. I created the "atavedata" branch with your modifications, so we are at step 3 !

**Comment by ZeusMarti** [comment]
Thanks Laurent, I had imagined the branch creation was an automatic process, sorry I learnt this the hard way. Let me know what you think about the atavedata branch then.

**Comment by ZeusMarti** [comment]
With the merge of #678 this issue is solved so I close it.
