### ISSUE TITLE
lattice element selection by index still acts on all FamName occurences

### ISSUE THREAD

**Issue by bi-veglia** [atcollab/at#402]
When trying to modify the KickAngle of a corrector selecting it by lattice index, the modification is applied to every element with the same FamName, ignoring the index. 
eg. the command 

>> ring[specific_corr_index].KickAngle = [Hangle, Vangle]

acts on the KickAngle of every element sharing the family name of the element at ring[specific_corr_index].

**Comment by swhite2401** [comment]
I am not sure this is your problem but in python when you write:
```
a = some_object
ring = [a, a, a, a]
```

`ring` will be populated with pointers to `a`, in case you want independent elements you have to make sure to add copies of `a` instead.

**Comment by bi-veglia** [comment]
I see. I'll think of some other ways around this, thanks
