### ISSUE TITLE
pyat wrong rbend entrance and exit angles from matlab m file

### ISSUE THREAD

**Issue by oscarxblanco** [atcollab/at#427]
Dear at developers,

when loading a matlab .m file using the at.load_m function, there is a wrong assignment to the EntranceAngle and ExitAngle for atrbend elements, setting them to zero.

This error is not present when loading the lattice from a matlab .mat file because the function find_class in pyat/at/load/utils.py copies both attribute values.

![bug_m_file](https://user-images.githubusercontent.com/108396048/176400292-a91a9461-17b8-43c0-b14d-1efb8f69279f.png)

**Comment by swhite2401** [comment]
Hello @oscarxblanco , interesting find! We will take a look. @lfarv did you see this?

**Comment by lfarv** [comment]
@oscarxblanco : thanks for reporting. I'm looking at that…

**Comment by lfarv** [comment]
Corrected in #430
