### ISSUE TITLE
atgeometry for pyAT

### ISSUE THREAD

**Issue by swhite2401** [atcollab/at#433]
If it does not exist, a function to get the elements 2D positions similar to `atgeometry()` would be a very useful addition to pyAT

**Comment by simoneliuzzo** [comment]
Dear @swhite2401, I have written such functions recently. I doubt they are at pyAT level. The file is here: 
https://gitlab.esrf.fr/BeamDynamics/newbooster/DBA_long/-/blob/master/booster_lattice_tools/survey.py

**Comment by swhite2401** [comment]
Very nice thanks!

**Comment by lfarv** [comment]
Added in #460
