### ISSUE TITLE
pyAT find_orbit outputs Nref x 6 instead of 6 x Nref

### ISSUE THREAD

**Issue by simoneliuzzo** [atcollab/at#466]
From the pyAT help the output of find_orbit is supposed to be (6, Nref)
![Screenshot 2022-08-24 at 16 39 11](https://user-images.githubusercontent.com/30342742/186447522-c057d067-9feb-4d6b-842f-9a1d063bf496.png)

but, using the command gives the transpose of this.
![Screenshot 2022-08-24 at 16 36 48](https://user-images.githubusercontent.com/30342742/186447682-3955988b-0ba6-47a1-b718-52ffd6999c93.png)

**Comment by lfarv** [comment]
Fixed in #478
