### ISSUE TITLE
Protect master

### ISSUE THREAD

**Issue by swhite2401** [atcollab/at#467]
Hello @lfarv, git is offering protection for the master (and has been telling me that it does for a while now!), in particular request for a PR and that all test pass to merge changes. Maybe we should activate these? What do you think?

**Comment by lfarv** [comment]
I agree with a protection against direct commits into "master" and forcing the use a pull request. On the other hand, I think we should keep the possibility to ignore test results and reviews for the moment. Test failures still happen…

**Comment by swhite2401** [comment]
Ok done

**Comment by lfarv** [comment]
@swhite: can you tell me where you modified the project settings? Thanks

**Comment by swhite2401** [comment]
Sure, see screenshot:

![image](https://user-images.githubusercontent.com/10014116/186603313-04a3b5e1-8cad-4d1b-9192-e5db92efbeef.png)
