### ISSUE TITLE
Frequency map with PyNAFF and patpass

### ISSUE THREAD

**Issue by oscarxblanco** [atcollab/at#553]
Dear all,

I have created a python function to calculate the frequency and diffusion maps for a given ring, using patpass parallel tracking and the PyNAFF python library.

I attach a copy of the function to this message in case it is of any use.
(Please remove the .txt name extension at the end of the filename)

[fmap_parallel_track.py.txt](https://github.com/atcollab/at/files/10489591/fmap_parallel_track.py.txt)

Best regards,
o

**Comment by swhite2401** [comment]
Handled in PR #556
