### ISSUE TITLE
plot_beta does not seem to have an option to display magnets names/indexes

### ISSUE THREAD

**Issue by simoneliuzzo** [atcollab/at#619]
pyAT plot_beta seems missing the equivalent of atplot(...,'labels', atgetcells(ring,'FamName','Q'))

**Comment by simoneliuzzo** [comment]
The version of `plot_synopt.py` in [pySC](https://github.com/lmalina/pySC/pull/5/files# )
pySC/core/plot_synopt.py

Provides a reduced version of this feature.

**Comment by swhite2401** [comment]
This was solved in #641 right, can we close it?
