### ISSUE TITLE
ATX makes matlab crash when Exact* integrators are used.

### ISSUE THREAD

**Issue by simoneliuzzo** [atcollab/at#697]
ATX makes matlab2020a crash when Exact* integrators are used.
for matlab 2021b, ATX does not crash matlab, but still computes NAN for modemittance when Exact* integrators are used.

**Comment by lfarv** [comment]
Hi @simoneliuzzo. Can you give an example of a ring which crashes, and details on the error message? 
I could not reproduce the problem, all my examples work as expected…

**Comment by lfarv** [comment]
@simoneliuzzo: Which platform are you running on?

I don't have Matlab 2020a any more, but I tried from 2020b to 2023b, and everything works well.

**Comment by simoneliuzzo** [comment]
I could not reproduce the problem today. I will open the issue again if it happens
