### ISSUE TITLE
B0 added twice in exactkickrad

### ISSUE THREAD

**Issue by swhite2401** [atcollab/at#736]
Hello @lfarv,

We we looking at the function ex_strthinkickrad in exactkickrad.c with @JeanLucPons and we don't understand why `B0` is added again in line 171:

https://github.com/atcollab/at/blob/d804a2d5e5c52fa7adb53afca80086697a277a9b/atintegrators/exactkickrad.c#L171

Is this a bug or are there good reasons for it to be added here?

Thanks!

**Comment by JeanLucPons** [comment]
Hello,
I was confused by the name B0 which does not refer the PolynomB[0].
ex_strthinkickrad() is always called by ExactMultiplolePass with B0 = 0.0
JL

**Comment by swhite2401** [comment]
Ah ok good, so when close this issue?
