### ISSUE TITLE
Possible Bug in random generators

### ISSUE THREAD

**Issue by swhite2401** [atcollab/at#841]
In #840 a bug with random generators was reported and fixed at the python level. 
The issue reported was that `ohmi_envelope()` would exist with a segmentation fault when an element with random number is present in the lattice, this issue appeared in #737.

This could be a sign of a profound bug in the random generators, could affect more function than just `ohmi_envelope()` and would need to be fixed at the C level.

**Comment by lfarv** [comment]
Corrected in #845
