### ISSUE TITLE
atx function fails with element EnergyLoss

### ISSUE THREAD

**Issue by oscarxblanco** [atcollab/at#865]
Dear all,
the matlab AT function `atx` fails when a ring contains an element `EnergyLoss`.
```matlab
Warning: Emittance computation failed:
'PassMethod' field must be a string
> In atx/go (line 208)
In atx (line 116) 
```
It seems to be solved if one includes the pass method in `atdiffmat`.
https://github.com/atcollab/at/blob/8aaae3e1f36bac5a5a2e47fc79088414b6dab10a/atmat/atphysics/Radiation/atdiffmat.m#L16-L18
Modified to
```matlab
newmethods = {'BndMPoleSymplectic4RadPass', ...
              'StrMPoleSymplectic4RadPass', ...
              'ExactMultipoleRadPass', ...
              'EnergyLossRadPass'};
```

**Comment by lfarv** [comment]
Fixed in #870
